### ISSUE TITLE
PHP Fatal Error on Single-Use Login URL Login Attempt

### ISSUE THREAD

**Issue by Amit-Biswas** [BrianHenryIE/bh-wp-autologin-urls#21] opened 2023-10-07 13:24 UTC
Hi Brian,

I’m frequently encountering a PHP Fatal error when attempting to log in as a user via a Single-use login URL. 

Debug Logs at the following locations:

1. https://realtor.link/wp-admin/tools.php?page=debug-log-manager
2. https://realtor.link/wp-admin/admin.php?page=bh-wp-autologin-urls-logs

Below are the error messages in the logs:

WordPress core
File: [/wp-includes/functions.php](https://github.com/WordPress/wordpress-develop/blob/6.3.1/src/wp-includes/functions.php)
Line: 5905
Logged at: Oct 7, 2023 - 01:22:58
(Logged 5 times)

**Error (PHP Fatal):**
Uncaught TypeError: Return value of BrianHenryIE\WP_Autologin_URLs\WP_Logger\API\API::get_backtrace() must be of the type array, but a string was returned.

Stack trace:
[#0](https://tickets.cloudways.com/hc/requests/503608) /wp-content/plugins/bh-wp-autologin-urls/vendor-prefixed/brianhenryie/bh-wp-logger/src/php/class-php-error-handler.php(123): BrianHenryIE\WP_Autologin_URLs\WP_Logger\API\API->get_backtrace()
[#1](https://tickets.cloudways.com/hc/requests/503608) [internal function]: BrianHenryIE\WP_Autologin_URLs\WP_Logger\PHP\PHP_Error_Handler->plugin_error_handler()
[#2](https://tickets.cloudways.com/hc/requests/503608) /wp-includes/class-wpdb.php(2459): mysqli_query()
[#3](https://tickets.cloudways.com/hc/requests/503608) /wp-includes/class-wpdb.php(2346): wpdb->_do_query()
[#4](https://tickets.cloudways.com/hc/requests/503608) /wp-includes/class-wpdb.php(2686): wpdb->query()
[#5](https://tickets.cloudways.com/hc/requests/503608) /home/833086.cloudwa in /wp-content/plugins/bh-wp-autologin-urls/vendor-prefixed/brianhenryie/bh-wp-logger/src/api/class-api.php on line 284

Plugin: [Magic Emails & Autologin URLs](https://wordpress.org/BrianHenryIE/bh-wp-autologin-urls)
File: /wp-content/plugins/bh-wp-autologin-urls/vendor-prefixed/brianhenryie/bh-wp-logger/src/api/class-api.php

**Comment by BrianHenryIE** [comment] 2023-10-07 17:03
Thanks. I came across this same error myself recently. What had happened in my case was the server/hosting had run out of disk space and a bug in my code was being hit in the case where a valid transient cache would return an empty value. To say: I [already have a fix which should help](https://github.com/BrianHenryIE/bh-wp-logger/commit/7bfd66b74e355d2832c45c4056b964fd75c797f2) and just need to push a new release.

Obviously something different is happening in your case. Let me look into this more and into your other issue on Monday and try get everything fixed then. Sorry for the delay.

**Comment by Amit-Biswas** [comment] 2023-10-08 06:42
I want to express my sincere gratitude for your ongoing efforts to enhance this plugin. 

It's wonderful to hear that you've already identified the error. I would be more than happy to provide any future bug reports, suggestions, or feedback for the bh-wp-autologin-urls plugin.

My WordPress password remains the same as I shared previously.

**Comment by BrianHenryIE** [comment] 2023-10-12 20:44
I wasn't able to learn anything about the root cause of this, but I'm confident it is fixed in the latest release: [v2.3.0](https://github.com/BrianHenryIE/bh-wp-autologin-urls/releases/tag/2.3.0). I've installed that on your site for you now.

**Closed by BrianHenryIE** 2023-10-12 20:44 UTC
